# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

workspace 'final project'

target 'final project' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for final project
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Kingfisher', '7.6.1'
  pod 'Swinject'
  pod 'SwinjectAutoregistration'
  pod 'ShimmerSwift'
  pod 'Alamofire', '5.4.4'
  pod 'SwiftLint'
  pod 'Cores', :git => "https://github.com/mfachrinuriza/CoresModule.git"
end